name: 機能リクエスト
title: "feat/[ユーザーストーリー]"
description: File a improvement report.
projects: ["truss-company/3"]
body:
  - type: markdown
    attributes:
      value: |
        trussサービスの新機能や機能改善を提案しよう！
        ※このissueはデフォルトでtrussプロジェクトに追加されます。

  - type: textarea
    id: context
    attributes:
      label: 提案の背景
      description: なぜその新機能・機能改善が必要なのか背景を教えてください。
    validations:
      required: true

  - type: textarea
    id: criteria-for-success
    attributes:
      label: 完了要件
      description: |
        その機能はなにが達成されれば完了となりますか？イメージがある場合は具体的に教えてください。
        もし完了要件が多くなる場合はissueの分割を検討してください。
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: 制約条件
      description: |
        その機能の実装にあたっての制約条件や考慮すべき事項があれば教えてください。
        例: 予算、期限、技術的制約、その他の制約条件
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: 自由記述
      description: その他、提案に関連する情報があれば自由に記述してください。
    validations:
      required: false
