name: 機能/改善リクエスト
title: "[ユーザーストーリー]"
description: File a improvement report.
body:
  - type: markdown
    attributes:
      value: |
        trussサービスの新機能や機能改善を提案しよう！

  - type: textarea
    id: context
    attributes:
      label: 提案の背景
      description: Why なぜその新機能・機能改善が必要なのか背景を教えてください。
    validations:
      required: true

  - type: textarea
    id: criteria-for-success
    attributes:
      label: 完了要件
      description: |
        What なにが達成されればこの機能は完了となりますか？
        もし完了要件が多くなる場合はissueの分割を検討してください。
      value: |
        - [ ] 
        - [ ]
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: 自由記述
      description: その他、提案に関連する情報があれば自由に記述してください。
    validations:
      required: false
