name: PR Review with ChatGPT
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout PR branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # PRのブランチをチェックアウト
          gh pr checkout ${{ github.event.pull_request.number }}

      - name: Run PR Review with ChatGPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # PRのdiffを取得
          pr_diff=$(gh pr diff --patch)

          # PRのdiffを JSON 形式にエスケープ
          escaped_pr_diff=$(echo "$pr_diff" | jq -Rs .)

          # JSON を正しく作成
          json_payload=$(jq -n --arg content "$escaped_pr_diff" '{
            model: "gpt-4o-mini",
            messages: [
              {role: "system", content: "あなたは有用なコードレビューアです。以下の変更をレビューし、フィードバックを日本語で提供してください。"},
              {role: "user", content: $content}
            ]
          }')

          # ChatGPT APIにリクエスト
          response=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$json_payload")

          review_comment=$(echo "$response" | jq -r '.choices[0].message.content')

          # PRにコメントを投稿
          gh pr comment ${{ github.event.pull_request.number }} --body "$review_comment"
