name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  labeler:
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
